name: hotspot
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  animated_text_kit: ^4.2.2
  bloc: ^8.1.2
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.7.1
  csv: ^5.0.2
  cupertino_icons: ^1.0.2
  easy_localization: ^3.0.2
  equatable: ^2.0.5
  firebase_auth: ^4.6.1
  firebase_core: ^2.13.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_launcher_icons: ^0.13.1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.3.0
  flutter_slidable: ^3.0.0
  flutter_svg: ^2.0.6
  get: ^4.6.1
  google_maps_flutter: ^2.3.1
  google_sign_in: ^6.1.4
  hydrated_bloc: ^9.1.2
  intl: ^0.18.0
  kakao_flutter_sdk: ^1.4.3
  like_button: ^2.0.5
  localization: ^2.1.0
  path_provider: ^2.0.15
  url_launcher: ^6.1.12
  uuid: ^3.0.7

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/csv/info.csv
    - assets/translations/
    - assets/images/
    - assets/svg/
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Suite
      fonts:
        - asset: assets/font/suite/SUITE-Variable.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
