// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6d8t7ZU3GWz9m7Kn-ABgvTMMBQTYKDGQ',
    appId: '1:981468579569:web:2e27f94803cfc799194b50',
    messagingSenderId: '981468579569',
    projectId: 'hotspot-fa426',
    authDomain: 'hotspot-fa426.firebaseapp.com',
    storageBucket: 'hotspot-fa426.appspot.com',
    measurementId: 'G-76M8VXFKRL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCInLg-fnePWbn0wep3gUIUb0wc55uniSs',
    appId: '1:981468579569:android:df7321faaaa528a4194b50',
    messagingSenderId: '981468579569',
    projectId: 'hotspot-fa426',
    storageBucket: 'hotspot-fa426.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAI1LP7J1JLWtxYY8RRbwH36nj4yuWoHB0',
    appId: '1:981468579569:ios:7139a9c4bfa7aaf6194b50',
    messagingSenderId: '981468579569',
    projectId: 'hotspot-fa426',
    storageBucket: 'hotspot-fa426.appspot.com',
    androidClientId: '981468579569-ba29u4372o8r5gbq4l6otg88mg9f1r44.apps.googleusercontent.com',
    iosClientId: '981468579569-6dr01t68771pj36u04f7ub2f0f6vga3g.apps.googleusercontent.com',
    iosBundleId: 'com.example.hotspot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAI1LP7J1JLWtxYY8RRbwH36nj4yuWoHB0',
    appId: '1:981468579569:ios:517f608a302e26b8194b50',
    messagingSenderId: '981468579569',
    projectId: 'hotspot-fa426',
    storageBucket: 'hotspot-fa426.appspot.com',
    androidClientId: '981468579569-ba29u4372o8r5gbq4l6otg88mg9f1r44.apps.googleusercontent.com',
    iosClientId: '981468579569-jc80dtg0k0boq1fc6qq9jfo3li8mfgut.apps.googleusercontent.com',
    iosBundleId: 'com.example.hotspot.RunnerTests',
  );
}
